export {
  DUE_SOON_WINDOWS,
  expiringNotes,
  type Freshness,
  freshnessOf,
  freshnessTimerDelay,
  type FreshnessOptions,
  type FreshnessStatus,
  type HasFrontmatter,
  isStale,
  MAX_TIMER_DELAY_MS,
  nextFreshnessChange,
  readStaleAfter,
  staleNotes,
} from "./freshness.js";
